version: '1.0'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: GHJ4gbQ0oCzk
      POSTGRES_DATABASE: verceldb
    networks:
      - kms
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: GHJ4gbQ0oCzk
      POSTGRES_DATABASE: verceldb
    networks:
      - kms
networks:
  kms:
